<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Activities' => 'Aktivitäten',
    'Backup failed: backup aborted.' => 'Backup fehlgeschlagen: Backup abgebrochen.',
    'Backup failed: network error.' => 'Backup fehlgeschlagen: Netzwerk Fehler.',
    'Backup failed: rdiff-backup failed (retval: {retval})' => 'Backup fehlgeschlagen: rdiff-backup fehlgeschlagen (Rückgabewert: {retval})',
    'Client state changed: {client_state}' => 'Client hat Status geändert: {client_state}',
    'Client state changed: {old} -> {new}' => 'Client hat Status geändert: {old} -> {new}',
    'Date' => 'Datum',
    'Description' => 'Bezeichnung',
    'Download failed: network error.' => 'Download fehlgeschlagen: Netzwerk Fehler.',
    'ID' => 'ID',
    'No activities found.' => 'Keine Aktivitäten gefunden.',
    'Restore failed: rdiff-backup failed (retval: {retval})' => 'Restore fehlgeschlagen: rdiff-backup fehlgeschlagen (Rückgabewert: {retval})',
    'Severity' => 'Fehlerstufe',
    'Ticket' => 'Ticket',
    'new activities; click to load' => 'neue Aktivitäten; Klicken zum laden',
    '"Bootup successful" message was not recieved, but client is successfully booted up. Client is now unlocked.' => '',
    'Backup failed: leaving ticket in abandoned state.' => '',
    'Exam download successfully requested by {ip} from Ticket with token {token}.' => '',
    'Exam download successfully requested by {ip} from {test_taker}.' => '',
    'Exam finished by Ticket with token {token}.' => '',
    'Exam finished by {test_taker}.' => '',
    'Exam result handed in.' => '',
    'Reset Grid' => '',
    'Restore failed: "{file}": No such file or directory.' => '',
    'Restore failed: network error.' => '',
    'Restore of {file} as it was as of {date} was successful.' => '',
    'Download failed: rsync failed (retval: {retval})' => '@@@@',
    'Exam download aborted (server side).' => '@@@@',
    'Exam download finished by {ip} from Ticket with token {token}.' => '@@@@',
    'Exam download finished by {ip} from {test_taker}.' => '@@@@',
    'backup aborted.' => '@@@@',
    'backup successful.' => '@@@@',
];
