<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '"Bootup successful" message was not recieved, but client is successfully booted up. Client is now unlocked.' => 'Die "Booten abgeschlossen" Nachricht wurde nicht empfangen, aber der Client hat erfolgreich gestartet. Der Client wurde entsperrt.',
    'Activities' => 'Aktivitäten',
    'Backup failed: leaving ticket in abandoned state.' => 'Backup fehlgeschlagen: Ticket wird fallengelassen.',
    'Client state changed: {client_state}' => 'Client hat Status geändert: {client_state}',
    'Client state changed: {old} -> {new}' => 'Client hat Status geändert: {old} -> {new}',
    'Date' => 'Datum',
    'Description' => 'Bezeichnung',
    'Download failed: rsync failed (retval: {retval})' => 'Herunterladen fehlgeschlagen: rsync fehlgeschlagen (Rückgabewert: {retval})',
    'Exam download aborted (server side).' => 'Herunterladen der Prüdung abgebrochen (serverseitig)',
    'Exam download finished by {ip} from Ticket with token {token}.' => 'Herunterladen der Prüfung abgeschlossen von {ip} des Tickets mit Token {token}.',
    'Exam download finished by {ip} from {test_taker}.' => 'Herunterladen der Prüfung abgeschlossen von {ip} von {test_taker}.',
    'Exam download successfully requested by {ip} from Ticket with token {token}.' => 'Prüfung wurde erfolgreich angefordert von {ip} des Tickets mit Token {token}.',
    'Exam download successfully requested by {ip} from {test_taker}.' => 'Prüfung wurde erfolgreich angefordert von {ip} von {test_taker}.',
    'Exam finished by Ticket with token {token}.' => 'Prüfung abgeschlossen vom Ticket mit Token {token}.',
    'Exam finished by {test_taker}.' => 'Prüfung abgeschlossen von {test_taker}.',
    'Exam result handed in.' => 'Prüfungsresultate wurden eingegeben.',
    'Fetch failed: backup aborted.' => 'Abruf fehlgeschlagen: Backup abgebrochen.',
    'Fetch failed: rsync failed (retval: {retval})' => 'Abruf fehlgeschlagen: rsync fehlgeschlagen (Rückgabewert: {retval})',
    'ID' => 'ID',
    'No activities found.' => 'Keine Aktivitäten gefunden.',
    'Reset Grid' => 'Raster zurücksetzen',
    'Restore failed: "{file}": No such file or directory.' => 'Wiederherstellung fehlgeschlagen: "{file}": Datei oder Verzeichnis nicht gefunden.',
    'Restore of {file} as it was as of {date} was successful.' => 'Wiederherstellung von {file} wie sie war ab {date} war erfolgreich.',
    'Severity' => 'Fehlerstufe',
    'Ticket' => 'Ticket',
    'new activities; click to load' => 'neue Aktivitäten; Klicken zum laden',
    '"Bootup successful" message was not recieved for a long time. Client is not reachable via its ip address {ip}. For more information, please check the {logfile}.' => 'Die "Booten abgeschlossen" Nachricht wurde lange nicht empfangen. Der Client ist nicht erreichbar über seine IP-Adresse {ip}. Für mehr Informationen, überprüfen Sie bitte das {logfile}.',
    '"Bootup successful" message was not recieved, but client is successfully booted up. Client cannot be unlocked. Error: {error}' => 'Die "Booten abgeschlossen" Nachricht wurde nicht empfangen, aber der Client hat erfolgreich gestartet. Der Client konnte nicht entsperrt werden. Fehler: {error}',
    'Backup failed: backup aborted, cause: {cause}' => 'Backup fehlgeschlagen: Backup abgebrochen, Grund: {cause}',
    'Backup failed: network error (ip:{ip}), {error}.' => 'Backup fehlgeschlagen: Netzwerk Fehler (IP:{ip}), {error}.',
    'Backup failed: rdiff-backup failed. For more information, please check the {logfile} (retval: {retval})' => 'Backup fehlgeschlagen: rdiff-backup fehlgeschlagen. Für mehr Informationen, überprüfen Sie bitte das {logfile} (Rückgabewert: {retval})',
    'Backup successful.' => 'Backup erfolgreich.',
    'Download failed: network error, {error}.' => 'Download fehlgeschlagen: Netzwerk Fehler, {error}.',
    'Exam download aborted (server side), cause: {cause}' => 'Prüfungsdownload abgebrochen (serverseitig), Grund: {cause}',
    'Restore failed: network error, {error}.' => 'Wiederherstellung fehlgeschlagen: Netzwerk Fehler, {error}.',
    'Restore failed: rdiff-backup failed. For more information, please check the {logfile} (retval: {retval})' => 'Wiederherstellung fehlgeschlagen: rdiff-backup fehlgeschlagen. Für mehr Informationen, überprüfen Sie bitte das {logfile} (Rückgabewert: {retval})',
    'Restore failed: restore aborted, cause: {cause}' => 'Wiederherstellung fehlgeschlagen: Wiederherstellung abgebrochen, Grund {cause}',
    'There was no successful backup since {n} minutes (the interval is set to {interval} minutes).' => 'Kein erfolgreiches Backup seit {n} Minuten (Der Intervall ist auf {interval} Minuten gesetzt).',
    'Backup failed: backup aborted.' => '@@Backup fehlgeschlagen: Backup abgebrochen.@@',
    'Backup failed: network error.' => '@@Backup fehlgeschlagen: Netzwerk Fehler.@@',
    'Backup failed: rdiff-backup failed (retval: {retval})' => '@@Backup fehlgeschlagen: rdiff-backup fehlgeschlagen (Rückgabewert: {retval})@@',
    'Download failed: network error.' => '@@Herunterladen fehlgeschlagen: Netzwerk Fehler.@@',
    'Restore failed: network error.' => '@@Wiederherstellung fehlgeschlagen: Netzwerk Fehler.@@',
    'Restore failed: rdiff-backup failed (retval: {retval})' => '@@Wiederherstellung fehlgeschlagen: rdiff-backup fehlgeschlagen (Rückgabewert: {retval})@@',
];
