<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'exam{n,plural,=0{s} =1{} other{s}} completed' => 'Prüfung{n,plural,=0{en} =1{} other{en}} abgeschlossen',
    'exam{n,plural,=0{s} =1{} other{s}} created' => 'Prüfung{n,plural,=0{en} =1{} other{en}} erstellt',
    'hour{n,plural,=0{s} =1{} other{s}} spent in exams' => 'Stund{n,plural,=0{en} =1{e} other{en}} in Prüfungen verbracht',
    'new activit{n,plural,=0{ies} =1{y} other{ies}}' => 'neue Aktivität{n,plural,=0{en} =1{} other{en}}',
    'running exam{n,plural,=0{s} =1{} other{s}}' => 'laufende Pürfung{n,plural,=0{en} =1{} other{en}}',
    '(not set)' => '(nicht gesetzt)',
    'Check your exam result!' => '',
    'Loading...' => '',
    'Login' => '',
    'Please contact us if you think this is a server error. Thank you.' => '',
    'The above error occurred while the Web server was processing your request.' => '',
    'The requested page does not exist.' => '',
    'You are not allowed to {action} this {item}.' => '',
    'Any' => '@@Alle@@',
    'Enter day...' => '@@Tag eingeben...@@',
];
