<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '(invalid date)' => '(ungültiges Datum)',
    '(not set)' => '(nicht gesetzt)',
    '<small>You have </small>{n_formatted}<small> exam{n,plural,=0{s} =1{} other{s}} created</small>' => '<small>Sie haben </small>{n_formatted}<small> Prüfung{n,plural,=0{en} =1{} other{en}} erstellt</small>',
    '<small>You have </small>{n_formatted}<small> new activit{n,plural,=0{ies} =1{y} other{ies}}</small>' => '<small> Sie haben </small>{n_formatted}<small> neue Aktivität{n,plural,=0{en} =1{} other{en}}</small>',
    'Check your exam result!' => 'Sehen Sie Ihr Prüfungsresultat an!',
    'Close' => 'Schliessen',
    'File not found.' => 'Datei nicht gefunden.',
    'For more information, please visit {link}.' => 'Für mehr Informationen, bitte besuchen Sie {link}.',
    'Learn more' => 'Mehr',
    'Loading...' => 'Lädt...',
    'Login' => 'Login',
    'Next step' => 'Nächster Schritt',
    'OFF' => 'AUS',
    'ON' => 'AN',
    'Please contact us if you think this is a server error. Thank you.' => 'Bitte kontaktieren Sie uns, falls Sie denken, dass das ein Server Fehler ist. Vielen Dank.',
    'Please wait...' => 'Bitte warten...',
    'Reload' => 'Neu laden',
    'Reload Page' => 'Seite neu laden',
    'Search' => 'Suche',
    'The above error occurred while the Web server was processing your request.' => 'Der Fehler oben passierte, während der Webserver Ihre Anfrage verarbeitete.',
    'The image could not be loaded.' => 'Das Bild konnte nicht geladen werden.',
    'The requested page does not exist.' => 'Die angeforderte Seite existiert nicht.',
    'The ressource is exclusively locked, please try again later.' => 'Die Ressource ist momentan gesperrt, bitte versuchen Sie es später noch einmal.',
    'Try out the new live overview to monitor running exams.' => 'Probieren Sie die neue Ansicht um Prüfungen zu überwachen.',
    'Welcome!' => 'Willkommen!',
    'You are not allowed to {action} this {item}.' => 'Sie sind nicht berechtigt zum {action} dieses {item}.',
    'exam{n,plural,=0{s} =1{} other{s}} completed' => 'Prüfung{n,plural,=0{en} =1{} other{en}} abgeschlossen',
    'hour{n,plural,=0{s} =1{} other{s}} spent in exams' => 'Stund{n,plural,=0{en} =1{e} other{en}} in Prüfungen verbracht',
    'keystrokes from Keylogger' => 'Tastatureingaben vom Keylogger',
    'running exam{n,plural,=0{s} =1{} other{s}}' => 'laufende Prüfung{n,plural,=0{en} =1{} other{en}}',
];
