<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '(invalid date)' => '(ungültiges Datum)',
    '(not set)' => '(nicht gesetzt)',
    '<small>You have </small>{n_formatted}<small> exam{n,plural,=0{s} =1{} other{s}} created</small>' => '<small>Sie haben </small>{n_formatted}<small> Prüfung{n,plural,=0{en} =1{} other{en}} erstellt</small>',
    '<small>You have </small>{n_formatted}<small> new activit{n,plural,=0{ies} =1{y} other{ies}}</small>' => '<small> Sie haben </small>{n_formatted}<small> neue Aktivität{n,plural,=0{en} =1{} other{en}}</small>',
    'Back' => 'Zurück',
    'Check your exam result!' => 'Sehen Sie Ihr Prüfungsresultat an!',
    'Close' => 'Schliessen',
    'File not found.' => 'Datei nicht gefunden.',
    'Finish' => 'Fertig',
    'For more information, please visit {link}.' => 'Für mehr Informationen, bitte besuchen Sie {link}.',
    'Learn more' => 'Mehr',
    'Loading...' => 'Lädt...',
    'Login' => 'Login',
    'Next step' => 'Nächster Schritt',
    'No screen capture found for this ticket.' => 'Kein Screen Capture für dieses Ticket gefunden',
    'OFF' => 'AUS',
    'ON' => 'AN',
    'Please contact us if you think this is a server error. Thank you.' => 'Bitte kontaktieren Sie uns, falls Sie denken, dass das ein Server Fehler ist. Vielen Dank.',
    'Record deleted successfully' => 'Eintrag erfolgreich gelöscht',
    'Reload' => 'Neu laden',
    'Reload Page' => 'Seite neu laden',
    'Search' => 'Suche',
    'Set' => 'Setzen',
    'The above error occurred while the Web server was processing your request.' => 'Der Fehler oben passierte, während der Webserver Ihre Anfrage verarbeitete.',
    'The requested page does not exist.' => 'Die angeforderte Seite existiert nicht.',
    'The ressource is exclusively locked, please try again later.' => 'Die Ressource ist momentan gesperrt, bitte versuchen Sie es später noch einmal.',
    'The ticket does not exist.' => 'Das Ticket existiert nicht.',
    'Try out the new live overview to monitor running exams.' => 'Probieren Sie die neue Ansicht um Prüfungen zu überwachen.',
    'Unable to determine the owner of the current object model ({route}).' => 'Nicht möglich den Besitzer des momentanen Objekts zu ermitteln ({route}).',
    'Welcome!' => 'Willkommen!',
    'You are not allowed to view this page. You need to have the following permission: "{permission} ({short})".' => 'Sie sind nicht berechtigt, diese Seite anzuzeigen. Sie benotigen die folgende Berechtigung: "{permission} ({short})".',
    'You are not allowed to view this property. You need to have the following permission: "{permission} ({short})".' => 'Sie sind nicht berechtigt, diese Eigenschaft anzuzeigen. Sie benotigen die folgende Berechtigung: "{permission} ({short})".',
    'exam{n,plural,=0{s} =1{} other{s}} completed' => 'Prüfung{n,plural,=0{en} =1{} other{en}} abgeschlossen',
    'hour{n,plural,=0{s} =1{} other{s}} spent in exams' => 'Stund{n,plural,=0{en} =1{e} other{en}} in Prüfungen verbracht',
    'keystrokes from Keylogger' => 'Tastatureingaben vom Keylogger',
    'not visible' => 'nicht sichtbar',
    'running exam{n,plural,=0{s} =1{} other{s}}' => 'laufende Prüfung{n,plural,=0{en} =1{} other{en}}',
    '{selected} <span style="color: #737373;">items</span>' => '{selected} <span style="color: #737373;">Elemente</span>',
    'Cancel' => 'Abbrechen',
    'Hand-in' => 'Abgeben',
    'Shutdown' => 'Herunterfahren',
    'Yes, hand-in my exam now!' => 'Ja, meine Prüfung jetzt abgeben!',
    'You are not allowed to view this page.' => 'Sie sind nicht berechtigt diese Seite anzuzeigen.',
    'You exam is requested for hand-in. Please wait while your data is transferred.' => 'Die Abgabe Ihrer Prüfung wurde angefordert. Bitte warten Sie solange Ihre Daten übertragen werden.',
    'Please wait...' => '@@Bitte warten...@@',
    'The image could not be loaded.' => '@@Das Bild konnte nicht geladen werden.@@',
    'You are not allowed to view this page. You need to have the following permission: "{permission}".' => '@@Sie sind nicht berechtigt diese Seite anzuzeigen. Sie brauchen die folgende Berechtigung: "{permission}".@@',
    'You are not allowed to {action} this {item}.' => '@@Sie sind nicht berechtigt zum {action} dieses {item}.@@',
];
