<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Back to token submission' => 'Zurück zur Token-Eingabe',
    'Continue' => 'Weiter',
    'Help' => 'Hilfe',
    'Insert your token here!' => 'Geben Sie hier Ihren Token ein!',
    'Please enter the token given on your exam sheet.' => 'Bitte geben Sie den Token auf dem Prüfungsblatt ein.',
    'Please wait, while your system is prepared' => 'Bitte warten Sie, während Ihr System vorbereitet wird.',
    'Request download again' => 'Download erneut anfordern',
    'The system setup is done. You can close this window now.' => 'Die Systemeinrichtung ist abgeschlossen. Sie könne dieses Fenster nun schliessen.',
];