<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Abort' => 'Abbrechen',
    'Back to token submission' => 'Zurück zur Token-Eingabe',
    'Confirm Exam Hand-in' => 'Abgabebestätigung der Prüfung',
    'Continue' => 'Weiter',
    'Exam Client' => 'Prüfungsclient',
    'Exam Status' => 'Prüfungsstatus',
    'Hand-in' => 'Abgabe',
    'Hand-in Exam' => 'Prüfung abgeben',
    'Help' => 'Hilfe',
    'Important!' => 'Wichtig!',
    'Insert your token here!' => 'Geben Sie hier Ihren Token ein!',
    'Please enter the token given on your exam sheet.' => 'Bitte geben Sie den Token auf dem Prüfungsblatt ein.',
    'Please notice, that once this process is initiated, you <b>cannot continue</b> with the exam. So, please make sure you <b>saved all documents</b> and <b>closed all open windows</b> before finishing your exam.' => 'Bitte beachten Sie, dass sobald dieser Prozess gestartet wurde, Sie <b>nichts mehr an Ihrer Abgabe verändern</b> können. Bitte stellen Sie sicher, dass Sie <b>alle Dokumente abgespeichert</b> und <b>alle offenen Fenster geschlossen</b> haben, bevor Sie Ihre Prüfung abgeben.',
    'Please wait, while your system is prepared' => 'Bitte warten Sie, während Ihr System vorbereitet wird',
    'Request download again' => 'Download erneut anfordern',
    'The system setup has failed.' => 'Das Systemeinrichtung îst fehlgeschlagen.',
    'The system setup is done. You can close this window now.' => 'Die Systemeinrichtung ist abgeschlossen. Sie könne dieses Fenster nun schliessen.',
    'You exam was handed-in successfully ({date}). You can close this window now.' => 'Ihre Prüfung wurde erfolgreich abgegeben ({date}). Sie können dieses Fenster nun schliessen.',
    'You exam was handed-in successfully. You can close this window now.' => 'Ihre Prüfung wurde erfolgreich abgegeben. Sie können dieses Fenster nun schliessen.',
    'You\'re about to hand-in your exam.' => 'Sie sind im Begriff Ihre Prüfung abzugeben.',
];
