<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Actions' => 'Aktionen',
    'Are you sure you want to kill this process?' => 'Sind Sie sicher, dass Sie diesen Prozess töten wollen?',
    'Daemons' => 'Hintergrundprozesse',
    'Description' => 'Beschreibung',
    'ID' => 'ID',
    'Kill' => 'Töten',
    'Load' => 'Last',
    'Load (Last 5 minutes)' => 'Last (Letzte 5 Minuten)',
    'Process' => 'Prozess',
    'Process ID' => 'Prozess ID',
    'Process UUID' => 'Prozess UUID',
    'Start Analyzer Daemon' => 'Starte Analyse Prozess',
    'Start Backup Daemon' => 'Starte Backup Prozess',
    'Start Daemon' => 'Starte Prozess',
    'Start Download Daemon' => 'Starte Download Prozess',
    'Started At' => 'Gestartet am',
    'State' => 'Status',
    'Stop' => 'Stoppen',
    'View' => 'Ansehen',
];
