<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Check to <b>save recovery information automatically every <code>n</code> minutes</b>. This command saves the information necessary to restore the current document in case of a crash (default location: <code>/home/user/.config/libreoffice/4/tmp</code>). Additionally, in case of a crash LibreOffice tries automatically to save AutoRecovery information for all open documents, if possible. (See <a target="_blank" href="https://help.libreoffice.org/Common/Saving_Documents_Automatically">LibreOffice Help</a>)' => 'Aktivieren um <b>Wiederherstellungsinformationen automatisch alle <code>n</code> Minuten abzuspeichern</b>. Diese Kommando speichert Informationen notwendig zur Wiederherstellung des aktuellen Dokuments im Falle eines Absturzes (Standardpfad: <code>/home/user/.config/libreoffice/4/tmp</code>). Zusätzlich versucht LibreOffice automatisch im Falle eines Absturzes AutoRecovery Informationen für alle offenen Dokumente abzuspeichern, falls möglich. (Siehe <a target="_blank" href="https://help.libreoffice.org/Common/Saving_Documents_Automatically/de">LibreOffice Hilfe</a>)',
    'HTTP URL Whitelist' => 'HTTP URL Whitelist',
    'If set, the system will <b>create screenshots every n minutes</b>. The Interval can be set in minutes. Those screenshots will appear in the Ticket view under the register "Screenshots". When generating exam results, they can also be included.' => 'Falls gesetzt, wird das System <b>alle n Minuten Bildschirmfotos anfertigen</b>. Das Intervall kann in Minuten gesetzt werden. Diese Bildschirmfotos werden in der Ticket Ansicht unter dem Register "Bildschirmfotos" angezeigt. Wenn Resultate generiert werden, können diese Bildschirmfotos auch hinzugefügt werden.',
    'If the <b>Always create backup copy</b> option is selected, the old version of the file is saved to the backup directory whenever you save the current version of the file. The backup copy has the same name as the document, but the extension is <code>.BAK</code>. If the backup folder (default location: <code>/home/user/.config/libreoffice/4/backup</code>) already contains such a file, it will be overwritten without warning. (See <a target="_blank" href="https://help.libreoffice.org/Common/Saving_Documents_Automatically">LibreOffice Help</a>)' => 'Falls die <b>Dokument automatisch speichern</b> Option ausgewählt ist, wird die alte Version des Dokuments ins Backup Verzeichnis gesichert, immer dann wenn die akutelle Version der Datei gespeichert wird. Die Sicherungskopie hat denselben Namen wie das Originaldokument, ausser mit der Endung <code>.BAK</code>. Falls das Sicherungsverzeichnis (Standardpfad: <code>/home/user/.config/libreoffice/4/backup</code>) bereits eine solche Datei beinhaltet, wird sie überschrieben ohne Warnung. (Siehe <a target="_blank" href="https://help.libreoffice.org/Common/Saving_Documents_Automatically/de">LibreOffice Hilfe</a>)',
    'Libreoffice' => 'Libreoffice',
    'Libreoffice: Always create backup copy' => 'Libreoffice: Sicherungskopie immer erstellen',
    'Libreoffice: Always create backup copy (to <code>{path}</code>)' => 'Libreoffice: Sicherungskopie immer erstellen (nach <code>{path}</code>)',
    'Libreoffice: Always create backup copy path' => 'Libreoffice: Sicherungskopie immer erstellen - Pfad',
    'Libreoffice: Save AutoRecovery information' => 'Libreoffice: Speichern von Autowiederherstellungsinformationen',
    'Libreoffice: Save AutoRecovery information (to <code>{path}</code> every <code>{interval}</code>)' => 'Libreoffice: Speichern von Autowiederherstellungsinformationen (nach <code>{path}</code> alle <code>{interval}</code>)',
    'Libreoffice: Save AutoRecovery information interval' => 'Libreoffice: Speichern von Autowiederherstellungsinformationen - Intervall',
    'Libreoffice: Save AutoRecovery information path' => 'Libreoffice: Speichern von Autowiederherstellungsinformationen - Pfad',
    'Maximum brightness' => 'Maximale Helligkeit',
    'Maximum screen brightness in percent. Notice that some devices have buttons to adjust screen brightness on hardware level. This cannot be controlled by this setting.' => 'Maximale Bildschirmhelligkeit in Prozent. Beachten Sie, dass einige Geräte Knöpfe haben, um die Helligkeit zu regeln auf Hardware-Ebene. Dies kann über diese Einstellung nicht kontrolliert werden.',
    'Screenshot interval' => 'Bildschirmfoto Intervall',
    'Take Screenshots' => 'Bildschirmfotos aufnehmen',
    'URLs given in this list will be allowed to visit by the exam student during the exam. Notice, due to this date, only URLs starting with <code>http://</code> are supported, therefore https://</code> URLs will be ignored. The URLs should be provided newline separated. The provided URLs are allowed even if the Firewall is enabled.' => 'Besuche auf URLs in dieser Liste werden erlaubt während der Prüfung. Die URLs sollten zeilenweise angegeben werden. Die angegebenen URLs werden erlaubt, auch wenn die Firewall aktiviert ist.',
];
