<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Automatic detection' => 'Automatisch ermitteln',
    'Choose a keymap ...' => 'Wählen Sie eine Tastaturbelegung ...',
    'Czech (Czechia)' => 'Tschechisch (Tschechien)',
    'English (United Kingdom)' => 'Englisch (Vereinigtes Königreich)',
    'English (United States) dvorak' => 'Englisch (Vereinigte Staaten) dvorak',
    'English (United States) for Ubuntu 12.04' => 'Englisch (Vereinigte Staaten) für Ubuntu 12.04',
    'French' => 'Französisch',
    'French (Canada)' => '@@Französisch (Kanada)@@',
    'French (Switzerland)' => 'Französisch (Schweiz)',
    'French dvorak' => 'Französisch dvorak',
    'German' => 'Deutsch',
    'German (Switzerland)' => 'Deutsch (Schweiz)',
    'Hungarian' => 'Ungarisch',
    'Italian' => 'Italienisch',
    'Mode' => 'Modus',
    'Norwegian' => 'Norwegisch',
    'Polish' => 'Polnisch',
    'Portuguese (Brazil)' => 'Portugiesisch (Brasilien)',
    'Portuguese (Portugal)' => 'Portugiesisch (Portugal)',
    'Provide a command' => 'Angabe eines Kommandos',
    'Romanian' => 'Rumänisch',
    'Russian' => 'Russisch',
    'Slovak (QWERTY)' => 'Slowakisch (QWERTY)',
    'Slovak (QWERTZ)' => 'Slowakisch (QWERTZ)',
    'Slovenian' => 'Slowenisch',
    'Spanish (Argentina)' => 'Spanisch (Argentinien)',
    'Spanish (Spain)' => 'Spanisch (Spanien)',
    'Swedish' => 'Schwedisch',
    'Turkish' => 'Türkisch',
    'Use options' => 'Angabe von Optionen',
];
