<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'A PHP extension stopped the file upload.' => '',
    'Failed to write file to disk.' => '',
    'Missing a temporary folder' => '',
    'No file was uploaded' => '',
    'The upload directory ({dir}) does not exist.' => '',
    'The upload directory ({dir}) is not writable.' => '',
    'The uploaded file exceeds the MAX_FILE_SIZE directive that was specified in the HTML form' => '',
    'The uploaded file exceeds the upload_max_filesize directive in php.ini' => '',
    'The uploaded file was only partially uploaded' => '',
    'There is no error, the file uploaded with success' => '',
    'Unknown File Upload Error' => '',
    'Unknown PHP File Upload Error: {error}' => '',
];
