<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'A PHP extension stopped the file upload.' => 'Eine PHP Erweiterung hat den Dateiupload gestoppt.',
    'Failed to write file to disk.' => 'Datei auf die Festplatte schreiben fehlgeschlagen.',
    'Missing a temporary folder' => 'Temporäres Verzeichnis fehlt',
    'No file was uploaded' => 'Datei wurde nicht hochgeladen',
    'The upload directory ({dir}) does not exist.' => 'Das Upload Verzeichnis ({dir}) existiert nicht.',
    'The upload directory ({dir}) is not writable.' => 'Das Upload Verzeichnis ({dir}) ist nicht schreibbar.',
    'The uploaded file exceeds the MAX_FILE_SIZE directive that was specified in the HTML form' => 'Die hochgeladene Datei überschreitet die MAX_FILE_SIZE Direktive, die im HTML Formular angegeben wurde',
    'The uploaded file exceeds the upload_max_filesize directive in php.ini' => 'Die hochgeladene Datei überschreitet die upload_max_filesize Direktive der php.ini Datei',
    'The uploaded file was only partially uploaded' => 'Die hochgeladene Datei wurde nur teilweise hochgeladen',
    'There is no error, the file uploaded with success' => 'Kein Fehler, die Datei wurde erfolgreich hochgeladen',
    'Unknown File Upload Error' => 'Unbekannter Dateiupload Fehler',
    'Unknown PHP File Upload Error: {error}' => 'Unbekannter PHP Dateiupload Fehler: {error}',
];
