<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Incorrect username or password.' => 'Falscher Benutzername oder Passwort.',
    'Login' => 'Login',
    'Please fill out the following fields to login:' => 'Bitte füllen Sie die folgenden Felder aus:',
    'To modify the users, please login as <strong>admin</strong>.' => 'Um Benutzer zu verändern, loggen Sie bitte als <strong>admin</strong> ein.',
    'You may login with <strong>admin/admin</strong> or <strong>teacher/teacher</strong>.' => 'Sie können mit <strong>admin/admin</strong> oder <strong>teacher/teacher</strong> einloggen.',
    'Authentication failed.' => 'Authentifizierung fehlgeschlagen.',
];
