<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Backup clients of tickets of all exams' => 'Klients aller Tickets sichern',
    'Backup clients of tickets of own exams' => 'Klients eigener Tickets sichern',
    'Create a live screenshot' => 'Ein Live Bildschirmfoto anlegen',
    'Create a ticket for all exams' => 'Ticket für alle Prüfungen erstellen',
    'Create a ticket for own exams' => 'Ticket für eigene Prüfungen erstellen',
    'Create a user' => 'Einen Benutzer erstellen',
    'Create an exam' => 'Eine Prüfung erstellen',
    'Delete all exams' => 'Alle Prüfungen löschen',
    'Delete all users' => 'Alle Benutzer löschen',
    'Delete own exams' => 'Eigene Prüfungen löschen',
    'Delete own user' => 'Eigenen Benutzer löschen',
    'Delete tickets of all exams' => 'Tickets aller Prüfungen löschen',
    'Delete tickets of own exams' => 'Tickets eigener Prüfungen löschen',
    'Index all activities' => 'Alle Aktivitäten auflisten',
    'Index all backup daemons' => 'Alle Backup Prozesse auflisten',
    'Index all exams' => 'Alle Prüfungen auflisten',
    'Index all users' => 'Alle Benutzer auflisten',
    'Index own activities' => 'Eigene Aktivitäten auflisten',
    'Index own exams' => 'Eigene Prüfungen auflisten',
    'Index tickets of all exams' => 'Tickets aller Prüfungen auflisten',
    'Index tickets of own exams' => 'Tickets eigener Prüfungen auflisten',
    'Kill backup daemons' => 'Backup Prozesse töten',
    'Reset password for all users' => 'Passwort aller Benutzer zurücksetzen',
    'Reset password for own user' => 'Passwort des eigenen Benutzers zurücksetzen',
    'Restore data to clients of tickets of all exams' => 'Datenwiederherstellung auf Klients von Tickets aller Prüfungen',
    'Restore data to clients of tickets of own exams' => 'Datenwiederherstellung auf Klients von Tickets eigener Prüfungen',
    'Start a new backup daemon' => 'Starte einen neuen Backup Prozess',
    'Stop backup daemons' => 'Stoppe einen Backup Prozess',
    'Update all exams' => 'Bearbeiten aller Prüfungen',
    'Update all users' => 'Bearbeiten aller Benutzer',
    'Update own exams' => 'Bearbeiten eigener Prüfungen',
    'Update own user' => 'Bearbeiten des eigenen Benutzers',
    'Update tickets of all exams' => 'Bearbeiten von Tickets aller Prüfungen',
    'Update tickets of own exams' => 'Bearbeiten von Tickets eigener Prüfungen',
    'View all users' => 'Alle Benutzer ansehen',
    'View backup daemons' => 'Backup Prozesse ansehen',
    'View own user' => 'Eigenen Benutzer ansehen',
    'View screenshots from a ticket' => 'Bildschirmfotos eines Tickets ansehen',
    'View the system configuration' => 'Die Systemkonfiguration ansehen',
    'View tickets of all exams' => 'Tickets aller Prüfungen ansehen',
    'View tickets of own exams' => 'Tickets eigener Prüfungen ansehen',
    'View/Monitor all exams' => 'Alle Prüfungen ansehen/überwachen',
    'View/Monitor own exams' => 'Eigene Prüfungen ansehen/überwachen',
];
