<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Backup clients of tickets of all exams' => '',
    'Backup clients of tickets of own exams' => '',
    'Create a live screenshot' => '',
    'Create a ticket for all exams' => '',
    'Create a ticket for own exams' => '',
    'Create a user' => '',
    'Create an exam' => '',
    'Delete all exams' => '',
    'Delete all users' => '',
    'Delete own exams' => '',
    'Delete own user' => '',
    'Delete tickets of all exams' => '',
    'Delete tickets of own exams' => '',
    'Index all activities' => '',
    'Index all backup daemons' => '',
    'Index all exams' => '',
    'Index all users' => '',
    'Index own activities' => '',
    'Index own exams' => '',
    'Index tickets of all exams' => '',
    'Index tickets of own exams' => '',
    'Kill backup daemons' => '',
    'Reset password for all users' => '',
    'Reset password for own user' => '',
    'Restore data to clients of tickets of all exams' => '',
    'Restore data to clients of tickets of own exams' => '',
    'Start a new backup daemon' => '',
    'Stop backup daemons' => '',
    'Update all exams' => '',
    'Update all users' => '',
    'Update own exams' => '',
    'Update own user' => '',
    'Update tickets of all exams' => '',
    'Update tickets of own exams' => '',
    'View all users' => '',
    'View backup daemons' => '',
    'View own user' => '',
    'View screenshots from a ticket' => '',
    'View the system configuration' => '',
    'View tickets of all exams' => '',
    'View tickets of own exams' => '',
    'View/Monitor all exams' => '',
    'View/Monitor own exams' => '',
];
