<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Avahi Port' => 'Avahi Port',
    'Avahi Protocol' => 'Avahi Protokoll',
    'Avahi Service File' => 'Avahi Dienst Datei',
    'Avahi TXT Records' => 'Avahi TXT Datensatz',
    'Host' => 'Host',
    'IP' => 'IP',
    'Options' => 'Optionen',
    'Port' => 'Port',
    'Server Configuation' => 'Server Konfiguration',
    'Server Status' => 'Server Status',
    'CPU usage' => 'CPU Nutzung',
    'DB connections' => 'DB Verbindungen',
    'Disk' => 'Datenträger',
    'I/O usage' => 'I/O Nutzung',
    'If one of the metrics below reaches 80% or more for a longer time or you experience performance issues, please consult the following resources for more information on how to solve these problems:' => 'Falls eine der unten aufgeführten Metriken 80% oder mehr über einen längeren Zeitraum erreicht oder Performance Probleme feststellbar sind, konsultieren Sie bitte folgende Hilfestellungen, für mehr Informationen, um diese Probleme zu lösen:',
    'Inotify instances' => 'Inotify Instanzen',
    'Inotify watches' => 'Inotify Watches',
    'Manual / Hardware Recommendations' => 'Benutzeranleitung / Hardware Empfehlungen',
    'Manual / Large exams' => 'Benutzeranleitung / Grosse Prüfungen',
    'Memory usage' => 'Speicher Nutzung',
    'Network' => 'Netzwerk',
    'Running daemons' => 'Hintergrundprozesse',
    'Swap usage' => 'Swap Nutzung',
    'Update Interval' => 'Update Intervall',
    'Webserver processes' => 'Webserver Prozesse',
    'connections' => 'Verbindungen',
    'daemons' => 'Daemons',
    'instances' => 'Instanzen',
    'processes' => 'Prozesse',
    'seconds' => 'Sekunden',
    'watches' => 'Watches',
    'Ø of {n} cores' => 'Ø von {n} Kernen',
];
