<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'A hint that is show in the login form for users attempting to login.' => 'Ein Hinweis am Login Formular für Benutzer, die einloggen wollen.',
    'A set of characters from which the token should be generated.' => 'Eine Menge an Zeichen, aus denen die Token generiert werden sollen.',
    'Apply' => 'Übernehmen',
    'Create' => 'Erstellen',
    'Default value' => 'Standardwert',
    'Description' => 'Beschreibung',
    'Duplicate character found. All characters must be unique.' => 'Doppelte Zeichen gefunden. Alle Zeichen müssen eindeutig sein.',
    'Edit' => 'Bearbeiten',
    'Edit Setting: {setting}' => 'Bearbeiten von {setting}',
    'Example tokens:' => 'Beispiel Tokens:',
    'ID' => 'ID',
    'If this is set the default value is used instead. No value is saved then.' => 'Falls das gesetzt ist, wird der Standard wiederhergestellt, dann wird auch kein Wert gespeichert.',
    'In this field, you can write <a target="_new" href="{link}">Markdown</a>.' => 'In diesem Feld können Sie auch <a target="_new" href="{link}">Markdown</a> schreiben.',
    'Key' => 'Schlüssel',
    'Login hint' => 'Login Hinweis',
    'Lower bound' => 'Untere Grenze',
    'Maximal daemons' => 'Maximale Anzahl Daemons',
    'Minimal daemons' => 'Minimale Anzahl Daemons',
    'Name' => 'Name',
    'Only alphanumeric characters (0-9, a-z, A-Z) are allowed.' => 'Nur alphanumerische Zeichen (0-9, a-z, A-Z) sind erlaubt.',
    'Preview' => 'Vorschau',
    'Reload Preview' => 'Vorschau aktualisieren',
    'Reset Grid' => 'Raster zurücksetzen',
    'Settings' => 'Einstellungen',
    'The length of the token, when generated in number of characters.' => 'Die Länge des Token in Anzahl Zeichen, wenn er neu generiert wird.',
    'The lower threshold in percent of the average load of all running daemons, such that one of them is stopped.' => 'Die untere Grenze in Prozent der durchschnittlichen Last aller laufenden Daemons, ab der einer von ihnen angehalten wird.',
    'The maximal number of running daemons, that are started by each other.' => 'Die maximale Anzahl laufender Daemons, die von einander gegenseitig gestartet werden sollen.',
    'The minimal number of running daemons, that are started if at least one daemon is running.' => 'Die minimale Anzahl Daemons, die gestartet werden wenn mindestens ein Daemon läuft.',
    'The time in seconds after the last successful backup, after which the ticket is left abandoned.' => 'Die Zeit in Sekunden seit dem letzen erfolgreichen Backup, nach der das Ticket als fallengelassen angesehen werden soll.',
    'The upper threshold in percent of the average load of all running daemons, such that a new daemons is started.' => 'Die obere Grenze in Prozent der durchschnittlichen Last aller laufenden Daemons, ab der neue Daemons gestartet werden sollen.',
    'There is no preview for this setting.' => 'Für diese Einstellung gibt es keine Vorschau.',
    'Ticket abandon time' => 'Ticket Vergessenszeit',
    'Token characters' => 'Token Zeichen',
    'Token length' => 'Länge des Tokens',
    'Type' => 'Typ',
    'Upper bound' => 'Obere Grenze',
    'Use default value' => 'Nehme Standardwert',
    'Value' => 'Wert',
    'You may login with **admin/admin** or **teacher/teacher**.<br>To modify the users, please login as **admin**.' => 'Sie können mit **admin/admin** oder **teacher/teacher** einloggen.<br>Um Benutzer zu verändern, loggen Sie bitte als **admin** ein.',
    'Date' => 'Datum',
];
