<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '\'{name}\' is not a role. Only roles can be deleted.' => '\'{name}\' ist keine Rolle. Nur Rollen können gelöscht werden.',
    '\'{name}\' is not a role. Only roles can be edited.' => '\'{name}\' ist keine Rolle. Nur Rollen können bearbeitet werden.',
    'A role is a collection of permissions given by explicit permissions or other roles. Select permissions and/or roles to be associated to this role.' => 'Eine Rolle ist eine Kollektion von Berechtigungen, gegeben durch explizite Zuweisung oder Zuweisung anderer Rollen. Wählen Sie Berechtigungen und/oder Rollen, die dieser Rolle zugeordnet sein sollen.',
    'A short description.' => 'Eine kurze Beschreibung',
    'A unique name for the role.' => 'Ein eindeutiger Name für die Rolle',
    'Apply' => 'Übernehmen',
    'Cannot add \'{child}\' as a child of {role}, because this produces a loop.' => 'Kann \'{child}\' nicht zu {role} hinzufügen, weil eine Enslosschleife resultieren würde.',
    'Create Role' => 'Rolle erstellen',
    'Created At' => 'Erstellt am',
    'Description' => 'Beschreibung',
    'Name' => 'Name',
    'No such permission or role: \'{item}\'.' => 'Keine solche Berechtigung oder Rolle: \'{item}\'.',
    'Only alphanumeric characters (0-9, a-z, A-Z) are allowed.' => 'Nur alphanumerische Zeichen (0-9, a-z, A-Z) sind erlaubt.',
    'Permissions' => 'Berechtigungen',
    'Reset Grid' => 'Raster zurücksetzen',
    'Rolename' => 'Rollenname',
    'Roles' => 'Rollen',
    'The \'{role}\' role is immutable and cannot be deleted.' => 'Die \'{role}\' Rolle ist unveränderlich und kann nicht gelöscht werden.',
    'The \'{role}\' role is immutable and cannot be edited.' => 'Die \'{role}\' Rolle ist unveränderlich und kann nicht bearbeitet werden.',
    'The attribute \'{attribute}\' is not editable. Remove the role and create a new one if you want to change that attribute.' => 'Das Attribut \'{attribute}\' is nicht editierbar. Entfernen Sie die Rollen und erstellen Sie sie neu, falls Sie dieses Attribut ändern mächten.',
    'The role \'{role}\' appears as a child in the role \'{parent_role}\'. Only roles without any associations can be deleted.' => 'Die Rolle \'{role}\' kommt als Berechtigung in der Rolle \'{parent_role}\' vor. Nur Rollen ganz ohne Zuweisungen können gelöscht werden.',
    'The role \'{role}\' appears in the group mapping of the authentication method {method}. Only roles without any associations can be deleted.' => 'Die Rolle \'{role}\' kommt in der Gruppenzugehörigkeit einer Authentifizierungsmethode {method} vor. Nur Rollen ohne weitere Verweise können gelöscht werden.',
    'The role \'{role}\' could not be added succesfully.' => 'Die Rolle \'{role}\' konnte nicht erfolgreich hinzugefügt werden.',
    'The role \'{role}\' could not be updated succesfully.' => 'Die Rolle \'{role}\' konnte nicht erfolgreich geändert werden.',
    'The role \'{role}\' does not exist (anymore).' => 'Die Rolle \'{role}\' existiert nicht (mehr).',
    'The role \'{role}\' has still permissions associated to. Only roles without permissions can be deleted.' => 'Die Rolle \'{role}\' hat immer nocht Berechtigungen zugewiesen. Nur Rollen ohne zugewiesene Bereichtigungen können gelöscht werden.',
    'The role \'{role}\' has still users associated to. Only roles without users can be deleted.' => 'Die Rolle \'{role}\' hat immer noch Benutzer zugewiesen. Nur Rollen ohne zugewiesene Benutzer können gelöscht werden.',
    'The role \'{role}\' was deleted successfully.' => 'Die Rolle \'{role}\' wurde erfolgreich gelöscht.',
    'The user has been deleted successfully.' => 'Der Benutzer wurde erfolgreich gelöscht.',
    'The user with id 1 cannot be deleted.' => 'Der Benutzer mit id 1 kann nicht gelöscht werden.',
    'The user with id 1 cannot be modified.' => 'Der Benutzers mit id 1 kann nicht bearbeitet werden.',
    'This permission or role does not exist.' => 'Diese Berechtigung oder Rolle existiert nicht.',
    'Updated At' => 'Bearbeitet am',
    'Username is already in use.' => 'Der Benutzername is bereits in Verwendung.',
    'You cannot delete yourself.' => 'Sie können sich nicht selbst löschen.',
    'You cannot modify a non local user.' => 'Sie können einen nicht-lokalen Benutzer nicht bearbeiten.',
    'You cannot modify yourself.' => 'Sie können sich selbst nicht bearbeiten.',
    'You cannot reset the password of a non local user.' => 'Sie können das Passwort eines nicht-lokalen Benutzers nicht zurücksetzen.',
    '\'{name}\' has still permissions associated to. Only roles without permissions can be deleted.' => '@@@@',
    '\'{name}\' has still users associated to. Only roles without users can be deleted.' => '@@@@',
    'Cannot add \'{role}\' as a child of itself.' => '@@Die Rolle \'{role}\' kann nicht als Berechtigung von sich selber hinzugefügt werden.@@',
    'Choose permission(s) for this role ...' => '@@Wählen Sie Berechtigung(en) für diese Rolle ...@@',
    'Select permissions to be associated to this role.' => '@@Wählen Sie Berechtigungen, die zu dieser Rolle assoziiert sein sollen.@@',
];
