<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'The user with id 1 cannot be modified.' => 'Der Benutzers mit id 1 kann nicht bearbeitet werden.',
    'The user with id 1 cannot be deleted.' => 'Der Benutzer mit id 1 kann nicht gelöscht werden.',
    'Username is already in use.' => 'Der Benutzername is bereits in Verwendung.',
    'You cannot delete yourself.' => 'Sie können sich nicht selbst löschen.',
    'You cannot modify a non local user.' => 'Sie können einen nicht-lokalen Benutzer nicht bearbeiten.',
    'You cannot modify yourself.' => 'Sie können sich selbst nicht bearbeiten.',
    'You cannot reset the password of a non local user.' => 'Sie können das Passwort eines nicht-lokalen Benutzers nicht zurücksetzen.',
];
