<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'The user with id 1 cannot be deleted.' => 'Der Benutzer mit id 1 kann nicht gelöscht werden.',
    'The user with id 1 cannot be modified.' => 'Der Benutzers mit id 1 kann nicht bearbeitet werden.',
    'Username is already in use.' => 'Der Benutzername is bereits in Verwendung.',
    'You cannot delete yourself.' => 'Sie können sich nicht selbst löschen.',
    'You cannot modify a non local user.' => 'Sie können einen nicht-lokalen Benutzer nicht bearbeiten.',
    'You cannot modify yourself.' => 'Sie können sich selbst nicht bearbeiten.',
    'You cannot reset the password of a non local user.' => 'Sie können das Passwort eines nicht-lokalen Benutzers nicht zurücksetzen.',
    '\'{name}\' appears in the group mapping of the authentication method {authMethod}. Only roles without any associations can be deleted.' => '',
    '\'{name}\' has still permissions associated to. Only roles without permissions can be deleted.' => '',
    '\'{name}\' has still users associated to. Only roles without users can be deleted.' => '',
    '\'{name}\' is not a role. Only roles can be deleted.' => '\'{name}\' ist keine Rolle. Nur Rollen können gelöscht werden.',
    '\'{name}\' is not a role. Only roles can be edited.' => '\'{name}\' ist keine Rolle. Nur Rollen können bearbeitet werden.',
    'A short description.' => 'Eine kurze Beschreibung',
    'A unique name for the role.' => 'Ein eindeutiger Name für die Rolle',
    'Apply' => 'Übernehmen',
    'Cannot add \'{role}\' as a child of itself.' => 'Die Rolle \'{role}\' kann nicht als Berechtigung von sich selber hinzugefügt werden.',
    'Choose permission(s) for this role ...' => 'Wählen Sie Berechtigung(en) für diese Rolle ...',
    'Create Role' => 'Rolle erstellen',
    'Created At' => 'Erstellt am',
    'Description' => 'Beschreibung',
    'Only alphanumeric characters (0-9, a-z, A-Z) are allowed.' => 'Nur alphanumerische Zeichen (0-9, a-z, A-Z) sind erlaubt.',
    'Permissions' => 'Berechtigungen',
    'Reset Grid' => 'Raster zurücksetzen',
    'Rolename' => 'Rollenname',
    'Roles' => 'Rollen',
    'Select permissions to be associated to this role.' => 'Wählen Sie Berechtigungen, die zu dieser Rolle assoziiert sein sollen.',
    'The \'{role}\' role is immutable and cannot be deleted.' => 'Die \'{role}\' Rolle ist unveränderlich und kann nicht gelöscht werden.',
    'The \'{role}\' role is immutable and cannot be edited.' => 'Die \'{role}\' Rolle ist unveränderlich und kann nicht bearbeitet werden.',
    'Updated At' => 'Bearbeitet am',
];
