<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Actions' => 'Aktionen',
    'Apply' => 'Übernehmen',
    'Are you sure you want to delete this item?' => 'Sind Sie sicher, dass Sie dieses Element löschen wollen?',
    'Choose role(s) ...' => 'Wählen Sie Rollen',
    'Choose roles associated to the user. If multiples roles are selected, the user will have the union of all permissions of all associated roles.' => 'Wählen Sie Rollen die zu diesen Benutzer assoziiert sein sollen. Falls Sie mehrere Rollen auswählen, wird der Benutzer Berechtigungen aller zugewiesenen Rollen haben.',
    'Create' => 'Erstellen',
    'Create Role' => 'Rolle erstellen',
    'Create User' => 'Benutzer erstellen',
    'Delete' => 'Löschen',
    'Edit' => 'Bearbeiten',
    'Edit Role: {id}' => 'Rolle bearbeiten: {id}',
    'Edit User: {id}' => 'Bearbeite Benutzer: {id}',
    'General' => 'Allgemein',
    'ID' => 'ID',
    'Inherited Permissions' => 'Vererbte Berechtigungen',
    'Last Visited' => 'Letzter Besuch',
    'No permissions found.' => 'Keine Berechtigungen gefunden.',
    'Password' => 'Passwort',
    'Please change your password.' => 'Bitte ändern Sie Ihr Passwort.',
    'Repeat Password' => 'Passwort wiederholen',
    'Reset' => 'Zurücksetzen',
    'Reset Grid' => 'Raster zurücksetzen',
    'Reset Password' => 'Passwort zurücksetzen',
    'Reset password for user: {user}' => 'Passwort für Benutzer zurücksetzen: {user}',
    'Role(s)' => 'Rolle(n)',
    'User has to change password at next login' => 'Der Benutzer muss sein Passwort beim nächsten Login ändern',
    'Username' => 'Benutzername',
    'Users' => 'Benutzer',
    'Interhited Permissions' => 'Geerbte Berechtigungen',
];
