#!/bin/sh

set -e

. /usr/share/debconf/confmodule

if [ -f /usr/share/dbconfig-common/dpkg/config.mysql ]; then
    . /usr/share/dbconfig-common/dpkg/config.mysql
    if ! dbc_go glados $@ ; then
        echo 'Automatic configuration using dbconfig-common failed!'
    fi
fi

db_version 2.0

db_go || true
