#!/bin/sh
# postinst script for glados
#
# see: dh_installdeb(1)

set -e

# summary of how this script can be called:
#        * <postinst> `configure' <most-recently-configured-version>
#        * <old-postinst> `abort-upgrade' <new version>
#        * <conflictor's-postinst> `abort-remove' `in-favour' <package>
#          <new-version>
#        * <postinst> `abort-remove'
#        * <deconfigured's-postinst> `abort-deconfigure' `in-favour'
#          <failed-install-package> <version> `removing'
#          <conflicting-package> <version>
# for details, see http://www.debian.org/doc/debian-policy/ or
# the debian-policy package

glados_datadir=/usr/share/glados
glados_statedir=/var/lib/glados
glados_rundir=/usr/share/glados/web/runtime
glados_assetdir=/usr/share/glados/web/assets
glados_logdir=/var/log/glados
glados_cfgdir=/etc/glados

avahi_install() {
    if [ -d /etc/avahi/services/ -a ! -e /etc/avahi/services/glados.service -a ! -L /etc/avahi/services/glados.service ] ; then
        #ln -s ../../glados/glados.service /etc/avahi/services/
        # avahi does not recognize links as service files
        mv /etc/glados/glados.service /etc/avahi/services/
        ln -s /etc/avahi/services/glados.service /etc/glados/glados.service
    fi
}

desktop_install() {
    if [ -d /usr/share/applications/ -a ! -e /usr/share/applications/glagos.desktop -a ! -L /usr/share/applications/glados.desktop ] ; then
        ln -s /etc/glados/glados.desktop /usr/share/applications/
    fi
}

phpini_install() {
	mkdir -p /etc/php/7.0/mods-available
	ln -sf /etc/glados/glados.ini /etc/php/7.0/mods-available/glados.ini
	phpenmod glados
}


php_inotify_install(){
    pecl upgrade inotify
    cat > /etc/php/7.0/mods-available/inotify.ini <<'EOF'
; configuration for php inotify module
; priority=20
extension=inotify.so
EOF

    phpenmod inotify
}

apache_install() {
    mkdir -p /etc/apache2/conf-available
    ln -sf ../../glados/apache.conf /etc/apache2/conf-available/glados.conf

    avahi_install
    desktop_install
    phpini_install
    php_inotify_install

    COMMON_STATE=$(dpkg-query -f '${Status}' -W 'apache2.2-common' 2>/dev/null | awk '{print $3}' || true)

    if [ -e /usr/share/apache2/apache2-maintscript-helper ] ; then
        . /usr/share/apache2/apache2-maintscript-helper
        apache2_invoke enmod rewrite
        apache2_invoke enconf glados
    elif [ "$COMMON_STATE" = "installed" ] || [ "$COMMON_STATE" = "unpacked" ] ; then
        [ -d /etc/apache2/conf.d/ ] && [ ! -L /etc/apache2/conf.d/glados.conf ] && ln -s ../conf-available/glados.conf /etc/apache2/conf.d/glados.conf
    fi
}

fix_permissions() {
    chown -R www-data:www-data "${glados_cfgdir}/auth.php"
    chown -R www-data:www-data "${glados_cfgdir}/auth_backup.php"
}

generate_cookievalidationkey() {
    # generate a random md5 hash
    KEY="$(cat /dev/urandom | tr -dc 'a-f0-9' | fold -w ${1:-32} | head -n 1)"
    sed -i "s/'cookieValidationKey' => '[0-9a-z]*'/'cookieValidationKey' => '${KEY}'/" \
        ${glados_datadir}/config/web.php
}

set_timezone() {
    # get the current timezone
    TZ="$(cat /etc/timezone | sed 's,/,\\\/,g')"
    sed -i "s/'timezone' => '[[:alnum:]\/]*'/'timezone' => '${TZ}'/" \
        ${glados_datadir}/config/web.php ${glados_datadir}/config/console.php
    sed -i "s/'defaultTimeZone' => '[[:alnum:]\/]*'/'defaultTimeZone' => '${TZ}'/" \
        ${glados_datadir}/config/web.php ${glados_datadir}/config/console.php
}

. /usr/share/debconf/confmodule

. /usr/share/dbconfig-common/dpkg/postinst.mysql
dbc_generate_include_owner="root:www-data"
dbc_generate_include_perms="0640"
dbc_generate_include=php:/etc/glados/config-db.php

if ! dbc_go glados $@ ; then
    echo 'Automatic configuration using dbconfig-common failed!'
fi

case "$1" in
    configure)
        if [ ! -d "$glados_logdir"   -a ! -L "$glados_logdir"   ]; then mkdir "$glados_logdir";   fi
        if [ ! -d "$glados_rundir"   -a ! -L "$glados_rundir"   ]; then mkdir "$glados_rundir";   fi
        if [ ! -d "$glados_assetdir" -a ! -L "$glados_assetdir" ]; then mkdir "$glados_assetdir"; fi
        if [ ! -d "$glados_statedir" -a ! -L "$glados_statedir" ]; then mkdir "$glados_statedir"; fi

        chown -R www-data:adm "$glados_logdir"
        chmod 2750 "$glados_logdir"
        chown -R www-data:www-data "$glados_rundir"
        chown -R www-data:www-data "$glados_assetdir"
        chown -R www-data:www-data "$glados_statedir"
        chmod 0700 "$glados_statedir"

        apache_install $1
        generate_cookievalidationkey
        set_timezone
        fix_permissions

        # Reload webserver in any case, configuration might have changed
        # Redirection of 3 is needed because Debconf uses it and it might
        # be inherited by webserver. See bug #446324.
        if [ -f /etc/init.d/apache2 ] ; then
            if [ -x /usr/sbin/invoke-rc.d ]; then
                invoke-rc.d apache2 reload 3>/dev/null || true
            else
                /etc/init.d/apache2 reload 3>/dev/null || true
            fi
        fi

    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1


esac

# dh_installdeb will replace this with shell code automatically
# generated by other debhelper scripts.

#DEBHELPER#

exit 0
