#!/bin/sh
# postrm script for glados

set -e

php_version=$(php -r 'list($m, $n)=explode(".", phpversion()); echo "$m.$n";') # gives MAJOR.MINOR

apache_remove() {
    COMMON_STATE=$(dpkg-query -f '${Status}' -W 'apache2.2-common' 2>/dev/null | awk '{print $3}' || true)

    if [ -e /usr/share/apache2/apache2-maintscript-helper ] ; then
        . /usr/share/apache2/apache2-maintscript-helper
        apache2_invoke disconf glados
    elif [ "$COMMON_STATE" = "installed" ] || [ "$COMMON_STATE" = "unpacked" ] ; then
        rm -f /etc/apache2/conf.d/glados.conf
    fi

    rm -f /etc/apache2/conf-available/glados.conf
}

php_inotify_remove(){
    pecl uninstall inotify
}

if [ -f /usr/share/debconf/confmodule ]; then
    . /usr/share/debconf/confmodule
fi
if [ -f /usr/share/dbconfig-common/dpkg/postrm.mysql ]; then
    . /usr/share/dbconfig-common/dpkg/postrm.mysql
    if ! dbc_go glados $@ ; then
        echo 'Automatic configuration using dbconfig-common failed!'
    fi
fi

if [ "$1" = "purge" ]; then
    rm -f /etc/glados/config-db.php
    if which ucf >/dev/null 2>&1; then
        ucf --debconf-ok --purge /etc/glados/config-db.php
        ucfr --purge glados /etc/glados/config-db.php
    fi
fi

if [ "$1" = "remove" ] || [ "$1" = "purge" ]; then
    if [ -f /usr/share/debconf/confmodule ]; then
        db_version 2.0

        apache_remove $1
        phpdismod glados

        php_inotify_remove $1
        phpdismod inotify

        # Redirection of 3 is needed because Debconf uses it and it might
        # be inherited by webserver. See bug #446324.
        if [ -f /etc/init.d/apache2 ] ; then
            if [ -x /usr/sbin/invoke-rc.d ]; then
                invoke-rc.d apache2 reload 3>/dev/null || true
            else
                /etc/init.d/apache2 reload 3>/dev/null || true
            fi
        fi
    fi

    if [ "$1" = "purge" ]; then
        # Possibly installed desktop file
        if [ -h /usr/share/applications/glados.desktop ] ; then
            rm -f /usr/share/applications/glados.desktop
        fi

        if [ -e /etc/avahi/services/glados.service ] ; then
            rm -f /etc/avahi/services/glados.service
        fi

        if [ -h /etc/php/${php_version}/mods-available/glados.ini ] ; then
            rm -f /etc/php/${php_version}/mods-available/glados.ini
        fi

        rm -f /etc/php/${php_version}/mods-available/inotify.ini
        rm -rf /etc/glados /var/lib/glados
    fi
fi

#DEBHELPER#

exit 0
